---
# util_server-role/tasks/install-dummy-interface.yml
# This will install the dummy ehternet interface, which we require
# to bind pihole to
- name: Configure the dummy ethernet interface in order to bind pi-hole to item.dst
  ansible.builtin.template:
    src: etc/network/interfaces.d/iface-dummy-dns.conf.j2
    dest: /etc/network/interfaces.d/iface-dummy-dns.conf
    mode: "0644"
  register: eth_dummy

# Restart of networking needs to take place immediately because
#  the existence of the dummy interface is a pre-req for pi-hole
- name: Restart networking if we just created the dummy interface # noqa: no-handler
  ansible.builtin.systemd_service:
    name: "networking.service"
    state: restarted
  when: eth_dummy.changed
