---
# tasks file for util_server
# This util_server should have tftp, preseed.cfg
# Then, it will take the latest netboot from the internet
# And configure the relevant files for it
# if no /var/www/html, then install a webserver (TODO) - for now, assume presence of webserver

# tftpd-hpa is the Trivial FTP server for Debian. It creates a default
# config and directory structure, which is fine for this purpose
- name: Ensure tftpd-hpa is installed
  ansible.builtin.apt:
    name: tftpd-hpa
    state: present

# I am assuming pi-hole is active on this machine as well, which depends on this
# directory to host its admin interface. We'll piggyback our preseed.cfg onto it
- name: Ensure /var/www/html exists
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: "0755"

# Note that the path (/) is relied upon by scripts. If you wish to host in a
# sub-folder, change this task and the previous task to reflect
# Also, change the txt.cfg file to correctly reflect this in /preseed/url
- name: Ensure preseed.cfg is in the /var/www/html folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/debian-preseed/preseed.cfg"
    dest: "/var/www/html"
    owner: root
    group: root
    mode: "0644"

- name: Obtain and unarchive the current netboot image. Configure netboot_url in vars or defaults
  ansible.builtin.unarchive:
    src: "{{ netboot_url }}"
    remote_src: true
    dest: /srv/tftp/
  when: netboot_download

# These with_items come from the netboot tarball and cannot be configured - leave them as-is
- name: Place the specific config files into the correct folder
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: "0644"
  with_items:
    - src: srv/tftp/debian-installer/amd64/boot-screens/syslinux.cfg.j2
      dst: /srv/tftp/debian-installer/amd64/boot-screens/syslinux.cfg
    - src: srv/tftp/debian-installer/amd64/boot-screens/txt.cfg.j2
      dst: /srv/tftp/debian-installer/amd64/boot-screens/txt.cfg

# Path is relied upon, the name of the .conf-file is arbitrary.
# Choose a name that makes sense to you
- name: Configure the dummy ethernet interface in order to bind pi-hole to item.dst
  ansible.builtin.template:
    src: etc/network/interfaces.d/iface-dummy-dns.conf.j2
    dest: /etc/network/interfaces.d/iface-dummy-dns.conf
    mode: "0644"
  register: eth_dummy

# Restart of networking needs to take place immediately because
#  the existence of the dummy interface is a pre-req for pi-hole
- name: Restart networking if we just created the dummy interface # noqa: no-handler
  ansible.builtin.systemd_service:
    name: "networking.service"
    state: restarted
  when: eth_dummy.changed

- name: Include pi-hole installation and configuration tasks
  ansible.builtin.import_tasks: pi-hole.yml
  when: do_pihole
