---
# tasks file for util_server
# This util_server should have tftp, preseed.cfg
# Then, it will take the latest netboot from the internet
# And configure the relevant files for it
# if no /var/www/html, then install a webserver (TODO) - for now, assume presence of webserver
- name: Ensure tftpd-hpa is installed
  ansible.builtin.apt:
    name: tftpd-hpa
    state: present

- name: Ensure /var/www/html exists
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: "0755"

- name: Ensure preseed.cfg is in the /var/www/html folder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/debian-preseed/preseed.cfg"
    dest: "/var/www/html"
    owner: root
    group: root
    mode: "0644"

- name: Obtain and unarchive the current netboot image
  ansible.builtin.unarchive:
    src: https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz
    remote_src: true
    dest: /srv/tftp/
  when: netboot_download

- name: Place the specific config files into the correct folder
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: "0644"
  with_items:
    - src: srv/tftp/debian-installer/amd64/boot-screens/syslinux.cfg.j2
      dst: /srv/tftp/debian-installer/amd64/boot-screens/syslinux.cfg
    - src: srv/tftp/debian-installer/amd64/boot-screens/txt.cfg.j2
      dst: /srv/tftp/debian-installer/amd64/boot-screens/txt.cfg

- name: Configure the dummy ethernet interface in order to bind pi-hole to item.dst
  ansible.builtin.template:
    src: etc/network/interfaces.d/iface-dummy-dns.conf.j2
    dest: /etc/network/interfaces.d/iface-dummy-dns.conf
    mode: "0644"
  register: eth_dummy

# Restart of networking needs to take place immediately because
#  the existence of the dummy interface is a pre-req for pi-hole
- name: Restart networking if we just created the dummy interface # noqa: no-handler
  ansible.builtin.systemd_service:
    name: "networking.service"
    state: restarted
  when: eth_dummy.changed

- name: Include pi-hole installation and configuration tasks
  ansible.builtin.import_tasks: pi-hole.yml
  when: refresh_pihole
