---
# util_server-role/tasks/pi-hole.yml
- name: Check wheter pi-hole is already installed
  ansible.builtin.stat:
    path: /etc/pihole/gravity.db
  register: pihole_db

- name: Feedback user on current pi-hole status
  ansible.builtin.debug:
    msg: "Pi-hole is already installed on this system"
  when: pihole_db.stat.exists

- name: Include tasks to actually (re-)install pihole
  ansible.builtin.import_tasks:
    file: install-pihole.yml
  when: install_pihole

# Do not start messing with the db if there is no db
- name: Import tasks to set-up the correct adlists, and white- and blacklists
  ansible.builtin.import_tasks:
    file: pihole-listmanage.yml
  when: install_pihole or pihole_db.stat.exists

- name: Create the dnsmasq config directory if it does not exist yet
  ansible.builtin.file:
    path: /etc/dnsmasq.d
    state: directory
    mode: "0755"

- name: Place the custom configuration into the dnsmasq.d directory
  ansible.builtin.template:
    src: etc/dnsmasq.d/99-pihole.conf.j2
    dest: /etc/dnsmasq.d/99-pihole.conf
    mode: "0644"

- name: Place the file with custom DNS entries into pihole configuration folder
  ansible.builtin.copy:
    dest: /etc/pihole/custom.list
    src: custom.list
    mode: "0644"
    owner: pihole
    group: pihole
    remote_src: false
