---
# role util_server/pihole-listmanage.yml

# Note that the order of DELETE is relevant, because of foreign key relations
- name: Manipulate the gravity database, first purging any possible current lists
  ansible.builtin.command:
    cmd: 'pihole-FTL sqlite3 /etc/pihole/gravity.db "DELETE FROM gravity; DELETE FROM adlist; DELETE FROM domainlist"'
  changed_when: true

# adlist is the table that contains the references to the block-lists
- name: Loop through all adlists, adding them to the database
  ansible.builtin.command:
    cmd: >
      pihole-FTL sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (id, address, enabled, date_added, date_modified,
       comment, number)
       VALUES ({{ item.id }}, '{{ item.address }}', {{ item.enabled }}, {{ item.date_added }}, {{ item.date_modified }},
        '{{ item.comment }}', {{ item.number }});"
  loop: "{{ adlists }}"
  changed_when: true
  notify: Update gravity

- name: Loop through all exception lists (whitelist and blacklist) and add them to the database
  ansible.builtin.include_tasks:
    file: process-lists.yml
  loop:
    - "{{ wl_exact }}"
    - "{{ wl_regex }}"
    - "{{ bl_exact }}"
    - "{{ bl_regex }}"
  loop_control:
    loop_var: process_lists
