---
- name: Check whether there already is a backup marker present
  ansible.builtin.stat:
    path: /etc/samba/backupmarker
  register: marker_stat_result

- name: Should there be no backup marker, create one that is really old to trigger refresh
  ansible.builtin.file:
    path: /etc/samba/backupmarker
    state: touch
    mode: "0777"
    modification_time: '200212311815.00'
  when: not marker_stat_result.stat.exists

- name: Re-read the stat for the marker, which now always exists
  ansible.builtin.stat:
    path: /etc/samba/backupmarker
  register: marker_stat_result

- name: Register the version.info's mtime into a properly formatted variable
  ansible.builtin.set_fact:
    marker_mtime: "{{ ('%Y%m%d-%H%M%S' | strftime(marker_stat_result.stat.mtime)) }}"

- name: Determine the age of the netboot image
  ansible.builtin.find:
    paths: /etc/samba
    pattern: 'backupmarker'
    age: "{{ backup_max_age }}"
    age_stamp: mtime
  register: backup_age

- name: Explain to the user what we found when looking at netboot image age
  ansible.builtin.debug:
    msg:
      - "Backup marker is {{ (now() - (marker_mtime | to_datetime('%Y%m%d-%H%M%S'))).days }} days old"
      - "Maximum allowed age is {{ backup_max_age }}"
