---
# tasks file for ad_backup - mountlocal
- name: Ensure cifs-utils is present on the local machine
  ansible.builtin.apt:
    name:
      - cifs-utils
    state: present

- name: Mount the backup folder
  ansible.posix.mount:
    path: "{{ local_backup_path }}"
    src: "{{ smb_backup_share }}"
    fstype: cifs
    opts: "credentials={{ cifcreds }},file_mode=0755,dir_mode=0755,rw,vers=3"
    state: ephemeral
    boot: false
  register: mounted
  ignore_errors: true
