---
# defaults file for virtualbox
vbox_apt_key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
vbox_repo_url: https://download.virtualbox.org/virtualbox/debian

# Used only for Debian/Ubuntu/Pop!_OS/Linux Mint. Switch 'stable' to 'nightly' if needed.
vbox_apt_suite: bookworm
vbox_apt_components: contrib

vbox_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

vbox_install_version: "7.1"
