---
# tasks file for pi_can

- name: Determine location of config-file
  ansible.builtin.stat:
    path: /boot/config.txt
  register: prebookwormconfig

- name: Set fact to correct boot config-file
  ansible.builtin.set_fact:
    pi_config: "{% if prebookwormconfig.stat.exists and not prebookwormconfig.stat.islnk %}/boot/config.txt{% else %}/boot/firmware/config.txt{% endif %}"

- name: Load the overlays for the PiCAN2-hat and enable SPI
  ansible.builtin.lineinfile:
    path: "{{ pi_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    insertafter: "{{ item.after | default('EOF') }}"
  with_items:
    - { regexp: "^#*?dtparam.*=.*spi.*", line: "dtparam=spi=on", after: "^[all]" }
    - { regexp: "^#*?dtoverlay.*=.*mcp2515-can0.*", line: "dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25", after: "^[all]" }
    - { regexp: "^#*?dtoverlay.*=.*spi-bcm2835.*", line: "dtoverlay=spi-bcm2835-overlay", after: "^[all]" }

- name: Place the readme-file in the home directory for the interactive user
  ansible.builtin.template:
    src: README.j2
    dest: "{{ interactive_home }}/README.txt"
    owner: root
    group: root
    mode: "0666"
