---
- name: Perform package repository update and perform full-upgrade
  hosts: debianlinux
  become: true

  tasks:
    - name: Update apt cache (when cache is older than a day) and full-upgrade.
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        cache_valid_time: 86400
      timeout: 600 # on slow raspberries, updating may take a long time

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: true
        purge: true
