---
- name: Perform default config on all hosts
  hosts: all
  # strategy: free # noqa: run-once[play]
  become: true
  # Please check group_vars for the appropriate values for these common roles
  roles:
    - common
    - log2ram
    - role: no_journal
      when: not enable_journaling | bool
    - role: powersave
      when: enable_powersave | bool
