---
- name: Show info on specific host
  hosts:
    - testenv
  become: true
  gather_facts: true
  roles:
    - waal70.authentik
  tasks:
    - name: Block for active group membership
      ansible.builtin.debug:
        msg: "Groups are: {{ group_names }}"
