---
- name: Show info on specific host
  hosts:
    - all
  become: true
  gather_facts: true
  tasks:
    - name: Block for active group membership
      ansible.builtin.debug:
        msg: "Groups are: {{ group_names }}"
