---
- name: Show info on specific host
  hosts:
    - all
  become: true
  tasks:
    - name: Debug info
      ansible.builtin.debug:
        msg:
          - "{{ groups['samba_ad_dc_servers'] }}"
          - "{{ groups['samba_ad_dc_servers'] | length }}"
          - "{{ hostvars[inventory_hostname]['andre'] | default('not defined') }}"
    - name: More debug
      ansible.builtin.debug:
        msg: "Yepsidaisies!"
      when: "'andre' in hostvars[inventory_hostname]"
