---

- name: Setup Proxmox VE over standard Debian bookworm
  hosts: proxmox_servers
  become: yes
  roles:
    - common
    - log2ram
    - pve

# - name: Setup Samba based ad-dc over standard Debian bookworm
#   hosts: samba_ad_dc_servers
#   become: yes
#   roles:
#     - common
#     - log2ram
#     - samba-ad-dc

# - name: Test stuff
#   hosts: testonly
#   become: true
#   roles:
#     - teststuff

  handlers:
  - name: Update APT cache
    apt:
      update_cache: yes
  
  - name: Update and upgrade APT
    apt:
      update_cache: yes
      upgrade: full

  - name: Restart systemd-journald
    systemd:
        name: systemd-journald
        state: restarted

  - name: Update GRUB configuration
    command: update-grub
    when: ansible_distribution == 'Debian'

