---


- name: Setup debian_servers
  hosts: debian_servers
  become: yes
  roles:
    - docker
    - portainer

- name: Bootstrap Raspberry Pi's on the network
  hosts: raspberry
  become: yes
  roles:
    - pi-common

- name: Add correct overlay to Raspberry pi
  hosts: hifiberry
  become: yes
  roles:
    - pi-hifiberry


# - name: Test stuff
#   hosts: testonly
#   become: true
#   roles:
#     - teststuff

  handlers:
  - name: Update APT cache
    apt:
      update_cache: yes
  
  - name: Update and upgrade APT
    apt:
      update_cache: yes
      upgrade: full

  - name: Restart systemd-journald
    systemd:
        name: systemd-journald
        state: restarted

  - name: Update GRUB configuration
    command: update-grub
    when: ansible_distribution == 'Debian'

