---

- name: Perform default config on all hosts
  hosts: all
  become: yes
  roles:
    - common
#    - no-journal
    - log2ram
    - powersave

- name: Setup Proxmox VE over standard Debian bookworm
  hosts: proxmox_servers
  become: yes
  roles:
    - role: pve
      when: pve_reset is undefined
    - role: pxe_prep
      when: pve_reset is defined

- name: Setup Samba based ad-dc over standard Debian bookworm
  hosts: samba_ad_dc_servers
  become: yes
  roles:
     - samba-ad-dc

- name: Bootstrap Raspberry Pi's on the network
  hosts: raspberry
  become: yes
  roles:
    - pi-common

- name: Add correct overlay to Raspberry pi
  hosts: hifiberry
  become: yes
  roles:
    - pi-hifiberry


# - name: Test stuff
#   hosts: testonly
#   become: true
#   roles:
#     - teststuff

  handlers:
  - name: Update APT cache
    apt:
      update_cache: yes
  
  - name: Update and upgrade APT
    apt:
      update_cache: yes
      upgrade: full

  - name: Restart systemd-journald
    systemd:
        name: systemd-journald
        state: restarted

  - name: Update GRUB configuration
    command: update-grub
    when: ansible_distribution == 'Debian'

