---
roles:
  # Install a role from Ansible Galaxy.
  # Install these roles using ansible-galaxy install -r requirements.yml
  - name: waal70.ansible_control
  - name: waal70.debian_common
  - name: waal70.debian_desktop
  - name: waal70.debian_omv
  - name: waal70.docker
  - name: waal70.eclipse
  - name: waal70.log2ram
  - name: waal70.no_journal
  - name: waal70.pi_common
  - name: waal70.portainer
  - name: waal70.powersave
  - name: waal70.pve
  - name: waal70.samba_ad_dc
  - name: waal70.util_server
  - name: waal70.virtualbox
  - name: waal70.vscode
