---
# file: site.yml
- name: Get a fresh certificate
  hosts:
    - localhost
  tasks:
    - name: Check whether there already is an SSH-key present
      ansible.builtin.stat:
        path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
      register: sshkey_stat_result

    - name: Should there be no SSH-key, create one that is really old to trigger refresh
      ansible.builtin.file:
        path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
        state: touch
        mode: "0600"
        modification_time: '200212311815.00'
      when: not sshkey_stat_result.stat.exists

    - name: Check the age of the SSH key
      ansible.builtin.stat:
        path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
      register: ssh_result

    - name: Register the mtime into a properly formatted variable
      ansible.builtin.set_fact:
        sshkey_mtime: "{{ ('%Y%m%d-%H%M%S' | strftime(ssh_result.stat.mtime)) }}"

    - name: Determine the age of the currently present SSH-key
      ansible.builtin.find:
        paths: "{{ private_repo }}/ssh-keys/ansible/"
        pattern: 'tmp-ansible-key'
        age: "12h"
        age_stamp: mtime
      register: sshkey_age

    - name: Explain to the user what we found when looking at SSH-keys
      ansible.builtin.debug:
        msg:
          - "SSH key is {{ ((now() - (sshkey_mtime | to_datetime('%Y%m%d-%H%M%S'))).total_seconds() / 3600) | round(1) }} hours old"
          - "Maximum allowed is 12h. I will {%if sshkey_age.files | length == 0 %}use the existing keys.{%else %}generate new keys.{%endif %}"

    - name: Run the SSH key signing script to get a fresh certificate # noqa: no-changed-when
      ansible.builtin.command: >
        ./firstrun.sh
      when: sshkey_age.files | length > 0

# - name: Assertions
#   ansible.builtin.import_playbook: playbooks/00-assertions.yml
# - name: Common configuration
#   ansible.builtin.import_playbook: playbooks/01-common.yml
# - name: Raspberry Pi setup
#   ansible.builtin.import_playbook: playbooks/02-pi.yml
# - name: Proxmox VE setup
#   ansible.builtin.import_playbook: playbooks/03-pve.yml
# - name: Active Directory Domain Controller
#   ansible.builtin.import_playbook: playbooks/04-ad-dc.yml
# - name: Outpost setup
#   ansible.builtin.import_playbook: playbooks/05-outpost.yml
# - name: TFTP Server setup
#   ansible.builtin.import_playbook: playbooks/06-tftp-server.yml
# - name: Pi-Hole setup and/or refresh
#   ansible.builtin.import_playbook: playbooks/06b-piholedns.yml
# - name: Ansible Control Node setup
#   ansible.builtin.import_playbook: playbooks/07-ansible-control-node.yml
# - name: Homeserver setup
#   ansible.builtin.import_playbook: playbooks/08-portainer-master.yml
# - name: Development Laptop setup
#   ansible.builtin.import_playbook: playbooks/09-dev-laptop.yml
# - name: Ensure services are present and running
#   ansible.builtin.import_playbook: playbooks/12-services.yml

# - name: Inform the user about which private key file is being used
#   hosts:
#     - all
#   tasks:
#     - name: Debug which private key file was used
#       ansible.builtin.debug:
#         msg: "{{ inventory_hostname }} has used {{ ansible_ssh_private_key_file }}"
