---
# file: site-clients.yml
# This file ensures configuration for client devices is done
- name: Ensure connectivity for Ansible
  hosts:
    - localhost
  tasks:
  # We choose include because the YAML will use discovered values
    - name: Include tasks to check for SSH key validity
      ansible.builtin.include_tasks: validate-ssh.yml
      run_once: true

- name: Assertions to validate this run
  ansible.builtin.import_playbook: playbooks/00-assertions.yml
- name: Common configuration for all Debian-based systems
  ansible.builtin.import_playbook: playbooks/20-clients-common.yml
- name: Configure laptops used for development
  ansible.builtin.import_playbook: playbooks/21-clients-dev-laptop.yml
- name: Configure airgapped systems
  ansible.builtin.import_playbook: playbooks/22-clients-airgap.yml

- name: Inform the user about which private key file is being used
  hosts:
    - all
  tasks:
    - name: Debug which private key file was used
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} has used {{ ansible_ssh_private_key_file }}"
