---
# file: site.yml
- name: Assertions
  ansible.builtin.import_playbook: 00-assertions.yml
- name: Common configuration
  ansible.builtin.import_playbook: 01-common.yml
- name: Raspberry Pi setup
  ansible.builtin.import_playbook: 02-pi.yml
- name: Proxmox VE setup
  ansible.builtin.import_playbook: 03-pve.yml
- name: Active Directory Domain Controller
  ansible.builtin.import_playbook: 04-ad-dc.yml
- name: Portainer Master setup
  ansible.builtin.import_playbook: 05-portainer-master.yml
- name: Utility Server setup
  ansible.builtin.import_playbook: 06-util-server.yml
- name: Ansible Control Node setup
  ansible.builtin.import_playbook: 07-ansible-control-node.yml
- name: Jumpserver setup
  ansible.builtin.import_playbook: 08-jumpserver.yml
- name: Development Laptop setup
  ansible.builtin.import_playbook: 09-dev-laptop.yml
