---
# file: site.yml
# Run ALL THE THINGS :)

- name: Site Infra
  ansible.builtin.import_playbook: site-infra.yml
- name: Site Apps Infra
  ansible.builtin.import_playbook: site-apps-infra.yml
- name: Site Apps Business
  ansible.builtin.import_playbook: site-apps-business.yml
- name: Site Clients
  ansible.builtin.import_playbook: site-clients.yml

- name: Inform the user about which private key file is being used
  hosts:
    - all
  tasks:
    - name: Debug which private key file was used
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} has used {{ ansible_ssh_private_key_file }}"
