---
# validate-ssh.yml
# This file checks whether Ansible is able to connect to the hosts
# by looking at the current age of the SSH key.
# If they are too old, it requests a new set of keys to be signed

- name: Check whether there already is an SSH-key present
  ansible.builtin.stat:
    path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
  register: sshkey_stat_result

- name: Should there be no SSH-key, create one that is really old to trigger refresh
  ansible.builtin.file:
    path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
    state: touch
    mode: "0600"
    modification_time: '200212311815.00'
  when: not sshkey_stat_result.stat.exists

- name: Check the age of the SSH key
  ansible.builtin.stat:
    path: "{{ private_repo }}/ssh-keys/ansible/tmp-ansible-key"
  register: ssh_result

- name: Register the mtime into a properly formatted variable
  ansible.builtin.set_fact:
    sshkey_mtime: "{{ ('%Y%m%d-%H%M%S' | strftime(ssh_result.stat.mtime)) }}"

- name: Determine the age of the currently present SSH-key
  ansible.builtin.find:
    paths: "{{ private_repo }}/ssh-keys/ansible/"
    pattern: 'tmp-ansible-key'
    age: "12h"
    age_stamp: mtime
  register: sshkey_age

- name: Explain to the user what we found when looking at SSH-keys
  ansible.builtin.debug:
    msg:
      - "SSH key is {{ ((now() - (sshkey_mtime | to_datetime('%Y%m%d-%H%M%S'))).total_seconds() / 3600) | round(1) }} hours old"
      - "Maximum allowed is 12h. I will {%if sshkey_age.files | length == 0 %}use the existing keys.{%else %}generate new keys.{%endif %}"

- name: Run the SSH key signing script to get a fresh certificate # noqa: no-changed-when
  ansible.builtin.command: >
    ./firstrun.sh
  when: sshkey_age.files | length > 0
