---
# title: role-samba-ad-dc
#
# Author: André
# Version: 1.0
# File: tasks/debian-bookworm-additional.yml
#
# Description: Install samba and *join* a domain. This file for non-primary domain controllers

- name: Transfer resolv.conf.j2 to /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"

- name: Join as additional domain controller because of smb_role
  ansible.builtin.command: >
    samba-tool domain join {{ smb_realm }} --dns-backend=SAMBA_INTERNAL DC
     -U"{{ smb_workgroup }}\{{ smb_username }}" --password={{ smb_password }}
     --option='idmap_ldb:use rfc2307 = yes'
  when:
    - smb_dc_result.failed
    - smb_role == 'additional'
    - not ad_database.stat.exists
  notify: Restart Samba
  changed_when: true

- name: Always stop services before conf file wizardry
  ansible.builtin.systemd_service:
    enabled: false
    state: stopped
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service
  when: smb_dc_result.failed

- name: Transfer krb5.conf.j2 to /etc/krb5.conf
  ansible.builtin.template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf
    mode: "0644"

- name: Always Enable Services
  ansible.builtin.systemd_service:
    enabled: true
    masked: false
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service

# - name: Obligatory reboot on joining domain, but only if join domain was executed in this run
#   ansible.builtin.reboot:
#     msg: "Ansible rebooting after joining domain"
#   when: ad_database.stat.exists == false

- name: Always restart samba-ad-dc.service and winbind
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - samba-ad-dc.service
    - winbind.service
