---
# Title: Role Samba4

- name: Build hosts file for SAMBA DC's # noqa: ignore-errors
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: .*{{ item }}$
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.{{ smb_realm }}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['samba_ad_dc_servers'] }}"
  ignore_errors: true

- name: Check whether this node already is a samba-ad-dc
  ansible.builtin.command: samba-tool domain info 127.0.0.1
  register: smb_dc_result
  ignore_errors: true
  changed_when: false

- name: "Preseed Kerberos version 5: krb5-config/default_realm"
  ansible.builtin.raw: echo krb5-config krb5-config/default_realm string {{ smb_realm }} | sudo debconf-set-selections
  when:
    - smb_dc_result.failed
  changed_when: true

- name: "Preseed Kerberos version 5: krb5-config/add_servers_realm"
  ansible.builtin.raw: echo krb5-config krb5-config/add_servers_realm string {{ smb_realm }} | sudo debconf-set-selections
  when:
    - smb_dc_result.failed
  changed_when: true

- name: Preseed PAM Configuration
  ansible.builtin.raw: echo libpam-runtime  libpam-runtime/profiles multiselect     unix, winbind, systemd, mkhomedir | sudo debconf-set-selections
  when:
    - smb_dc_result.failed
  changed_when: true

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - krb5-user
      - samba
      - smbclient
      - winbind

- name: Remove (old) Samba configuration
  ansible.builtin.file:
    path: /etc/samba/smb.conf
    state: absent
  when:
    - smb_dc_result.failed

- name: Transfer smb.conf.j2 to /etc/samba/smb.conf
  ansible.builtin.template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: "0644"

# The default comes from ./defaults/main.yml. This will override if a second server is specified
- name: Overwrite secondary dns if appropriate
  ansible.builtin.set_fact:
    smb_secondary_dns: "{{ hostvars[groups['samba_ad_dc_servers'][1]]['ansible_host'] }}"
  when: groups['samba_ad_dc_servers'] | length > 1

- name: Back-up the initial /etc/krb5.conf to /etc/krb5.conf.initial # noqa: ignore-errors
  ansible.builtin.copy:
    src: /etc/krb5.conf
    dest: /etc/krb5.conf.initial
    remote_src: true
    force: false
    mode: "0644"
  ignore_errors: true

- name: Edit Fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: errors=remount-ro 0
    replace: user_xattr,acl,barrier=1,errors=remount-ro,relatime 0
    backup: true

- name: Check whether the AD database exists
  ansible.builtin.stat:
    path: /var/lib/samba/private/sam.ldb
  register: ad_database
