---
# title: role-samba-ad-dc
#
# Author: André
# Version: 1.0
# File: tasks/debian-bookworm-primary.yml
#
# Description: Install samba and provision a domain. This file for primary domain controllers

- name: Transfer resolv.conf.j2 to /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"

- name: Set {{ ansible_hostname }} as primary domain controller because of smb_role={{ smb_role }} # noqa: name[template]
  ansible.builtin.command: >
    samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL
     --site={{ smb_site }} --realm={{ smb_realm }} --domain={{ smb_workgroup }}
      --adminpass={{ smb_password }}
  when:
    - smb_dc_result.failed
    - smb_role=="primary"
    - not ad_database.stat.exists
  notify: Restart Samba
  changed_when: true

- name: Disable Services
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service
  when:
    - smb_dc_result.failed

- name: Back-up the initial /etc/krb5.conf to /etc/krb5.conf.initial
  ansible.builtin.copy:
    src: /etc/krb5.conf
    dest: /etc/krb5.conf.initial
    remote_src: true
    force: false
    mode: "0644"
  when:
    - smb_dc_result.failed

- name: Copy /var/lib/samba/private/krb5.conf to /etc/krb5.conf
  ansible.builtin.copy:
    src: /var/lib/samba/private/krb5.conf
    remote_src: true
    dest: /etc/krb5.conf
    mode: "0644"
    force: true

- name: Always Enable Services
  ansible.builtin.systemd_service:
    enabled: true
    masked: false
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service

- name: Always restart samba-ad-dc.service
  ansible.builtin.systemd_service:
    name: samba-ad-dc.service
    state: reloaded

- name: Edit Fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: errors=remount-ro 0
    replace: user_xattr,acl,barrier=1,errors=remount-ro,relatime 0
    backup: true
  when:
    - smb_dc_result.failed

- name: Ease up on the password requirements
  ansible.builtin.import_tasks: samba-passreqs.yml
