---
# title: samba-ad-dc
#

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

# Always run shared tasks:
- name: Always import shared tasks
  ansible.builtin.import_tasks: debian-bookworm-shared.yml

- name: For Debian bookworm - primary
  ansible.builtin.import_tasks: debian-bookworm-primary.yml
  when:
    - smb_role == "primary"
    - ansible_architecture == "x86_64"
    - ansible_distribution_release == "bookworm"

- name: For Debian bookworm - additional
  ansible.builtin.import_tasks: debian-bookworm-additional.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_release == "bookworm"
    - ansible_architecture == "x86_64"

- name: Import tasks to set sysvol sync
  ansible.builtin.import_tasks: sysvol-sync.yml
