# Packages as per https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_12_Bookworm#Install_the_Proxmox_VE_packages
---
- name: Stage packages needed for base PVE installation
  ansible.builtin.set_fact:
    _pve_install_packages:
      - proxmox-ve
      - postfix
      - open-iscsi
      - chrony

- name: Stage any extra packages the user has specified
  ansible.builtin.set_fact:
    _pve_install_packages: "{{ _pve_install_packages | union(pve_extra_packages) }}"
