---
# tasks file for unifi_info
# The API is not officially documented. This module is based upon:
# https://ubntwiki.com/products/software/unifi-controller/api

- name: Generate authentication token
  ansible.builtin.uri:
    url: "{{ controller_login }}"
    method: POST
    return_content: true
    body_format: json
    body:
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"
      remember: "true"
    validate_certs: false
  register: auth_token

- name: Get info on active stations (ie. connected client devices, currently holding an IP-address)
  ansible.builtin.uri:
    url: "{{ controller_api }}/s/{{ controller_site }}/stat/sta"
    method: GET
    headers:
      Cookie: "{{ auth_token.cookies_string }}"
    return_content: true
    validate_certs: false
  register: response

- name: Transform the response into a format containing hardware address, ip address, hostname and manufacturer
  ansible.builtin.set_fact:
    livelist: "{{ response.json | default({'data': {}}) |
       community.general.json_query('data[*].{mac: mac, ansible_host: not_null(ip, last_ip), dhcp_hostname: hostname, oui: oui}') }}"

# livelist will have this form:
#         {
#             "ansible_host": "172.16.29.202",
#             "hostname": "Woonkamer",
#             "mac": "dc:56:e7:3d:eb:fd",
#             "oui": "Apple"
#         },
#         {
#             "ansible_host": "172.16.99.221",
#             "hostname": "",
#             "mac": "8a:e8:6e:4a:23:93",
#             "oui": ""
#         },

- name: Further reduce the transformed list of live clients to only those that have an entry in the inventory
  ansible.builtin.set_fact:
    livelist_known: "{{ (livelist_known | default([])) + [item] }}"
  with_items: "{{ livelist }}"
  when: item.mac in maclist

- name: Create the baselists that we will base further processing on
  ansible.builtin.set_fact:
    # ip will contain a list with only known IP-addresses
    ip: "{{ livelist_known | map(attribute='ansible_host') | list }}"
    # mac will contain a list with only the hardware addresses
    mac: "{{ livelist_known | map(attribute='mac') | list }}"
    # transform the inventory list into a list by group name
    il_groups: "{{ maclist | from_json | items2dict(key_name='mac', value_name='group') }}"
    # transform the inventory list into a list by hostname
    il_names: "{{ maclist | from_json | items2dict(key_name='mac', value_name='name') }}"

- name: Create the singular baselists
  ansible.builtin.set_fact:
    il_group: "{{ mac | map('extract', il_groups) | list }}"
    il_name: "{{ mac | map('extract', il_names) | list }}"

- name: Transform into dictionaries format
  ansible.builtin.set_fact:
    # transform the singular groups into dictionary objects
    il_group_dict: "{{ dict(mac | zip(il_group)) }}"
    # also for the name list
    il_name_dict: "{{ dict(mac | zip(il_name)) }}"

- name: Transform into Ansible list format
  ansible.builtin.set_fact:
    # now transform the dicts into ansible lists:
    il_group_list: "{{ il_group_dict | dict2items(key_name='mac', value_name='group') }}"
    il_name_list: "{{ il_name_dict | dict2items(key_name='mac', value_name='name') }}"

- name: Create the final result
  ansible.builtin.set_fact:
    # merge the two in order to create the final result
    # the two yield the same result. One uses community.general.lists_mergeby, which you may or may not like
    # result_final: "{{ [livelist_known, il_group_list, il_name_list] | community.general.lists_mergeby('mac') }}"
    result_final: "{{ livelist_known | zip(il_group_list) | zip(il_name_list) | map('flatten') | map('combine') | list }}"

- name: Debug
  ansible.builtin.debug:
    msg:
      - "ip: {{ ip }}"
      - "mac: {{ mac }}"
      - "il_groups: {{ il_groups }}"
      - "il_names: {{ il_names }}"
      - "il_group: {{ il_group }}"
      - "il_name: {{ il_name }}"
      - "il_group_dict: {{ il_group_dict }}"
      - "il_name_dict: {{ il_name_dict }}"
      - "il_group_list: {{ il_group_list }}"
      - "il_name_list: {{ il_name_list }}"
      - "============================FINAL RESULT================================"
      - "{{ result_final }}"
      - "{{ auth_token.cookies_string }}"

# { "_meta": {
#      "hostvars": {
#          "adpi0": {
#               "ansible_host": "ip-address"
#                   }
#                 }
#             },
#   "groupname": {
#        hosts: ["adpi0", "adpi1"]

#  }
#
