---
- name: Add Proxmox pve-no-subscription repository
  apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
    state: present
  notify: Update APT cache
