---
# powersave Intel.yml
- name: Ensure powertop is installed
  ansible.builtin.apt:
    name: powertop
    state: present

- name: Check whether service file already is there
  ansible.builtin.stat:
    path: /etc/systemd/system/powertop.service
  register: ps

- name: Place service file to run at startup for powertop
  ansible.builtin.template:
    src: etc/systemd/system/powertop.service.j2
    dest: /etc/systemd/system/powertop.service
    owner: root
    group: root
    mode: "0644"
  when: not ps.stat.exists

- name: Trigger enabling of service and daemon-reload for powertop
  ansible.builtin.systemd_service:
    daemon-reload: true
    enabled: true
    state: reloaded
    name: powertop.service
  when: not ps.stat.exists

- name: Ensure cpufrequtils is installed
  ansible.builtin.apt:
    name: cpufrequtils
    state: present

- name: Set powersave governor to powersave if currently other setting
  ansible.builtin.template:
    src: etc/default/cpufrequtils.j2
    dest: /etc/default/cpufrequtils
    owner: root
    group: root
    mode: "0644"
  when: (cpu_governors is not search("powersave"))
