---
# tasks file for powersave
- name: Import powersave-governor tasks for the powersave-role
  ansible.builtin.import_tasks: powersave_governor.yml

- name: Configure further poweroptions agnostically
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/{{ ansible_local.cpu_info.systemtype }}.yml"
    - "{{ role_path }}/tasks/unsupported-systemtype.yml"
