---
# tasks file for powersave
- name: Import powertop tasks for the powersave-role
  ansible.builtin.import_tasks: powertop.yml

- name: Import powersave-governor tasks for the powersave-role
  ansible.builtin.import_tasks: powersave_governor.yml
