---
- name: Ensure linux-cpupower is installed
  ansible.builtin.apt:
    name: linux-cpupower
    state: present

- name: Check current powersave governor
  ansible.builtin.command: cpupower frequency-info --policy
  register: governor_output
  ignore_errors: true
  changed_when: false

- name: Create variable for governor check
  ansible.builtin.set_fact:
    cpu_governors: "{{ governor_output.stdout_lines }}"

- name: Print current governors
  ansible.builtin.debug:
    var: cpu_governors

- name: Ensure cpufrequtils is installed
  ansible.builtin.apt:
    name: cpufrequtils
    state: present

- name: Set powersave governor to powersave if currently other setting
  ansible.builtin.template:
    src: etc/default/cpufrequtils.j2
    dest: /etc/default/cpufrequtils
    owner: root
    group: root
    mode: "0644"
  when: cpu_governors is not search("powersave")

# when check includes likely virtualized machines that will have "Unable to determine current policy"
- name: Reboot to set new governor, but only if changed
  ansible.builtin.reboot:
  when: ((cpu_governors is not search("powersave")) and (cpu_governors is not search("Unable to determine")))
