---
- name: Ensure linux-cpupower is installed
  ansible.builtin.apt:
    name: linux-cpupower
    state: present

- name: Check current powersave governor
  ansible.builtin.command: cpupower frequency-info --policy
  register: governor_output
  ignore_errors: true
  changed_when: false

- name: Create variable for governor check
  ansible.builtin.set_fact:
    cpu_governors: "{{ governor_output.stdout_lines }}"

- name: Print current governors
  ansible.builtin.debug:
    var: cpu_governors
