---
# tasks file for debian_omv
- name: Add openmediavault apt repository source
  ansible.builtin.deb822_repository:
    name: openmediavault
    types: [deb]
    uris: https://packages.openmediavault.org/public
    suites: "{{ omv_version }}"
    components: main
    signed_by: https://packages.openmediavault.org/public/archive.key
    architectures: "{{ omv_arch }}"
    enabled: true

- name: Install openmediavault package
  ansible.builtin.apt:
    name: openmediavault
    install_recommends: false
    allow_downgrade: true
    state: latest
    update_cache: true

# this command is needed to initialize the system
- name: "Configure OMV DB"
  ansible.builtin.command: "/usr/sbin/omv-confdbadm populate"
  when: omv_first_install
  changed_when: true
