---
# tasks file for debian_omv
# - name: Add openmediavault apt repository source
#   ansible.builtin.deb822_repository:
#     name: openmediavault
#     types: [deb]
#     uris: https://packages.openmediavault.org/public
#     suites: "{{ omv_version }}"
#     components: main
#     signed_by: https://packages.openmediavault.org/public/archive.key
#     architectures: "{{ omv_arch }}"
#     enabled: true
- name: Install gpg
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true

- name: Add OMV gpg signing key
  ansible.builtin.apt_key:
    url: https://packages.openmediavault.org/public/archive.key
    state: present

- name: Add OMV package repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.openmediavault.org/public {{ omv.version }} main
    state: present
    filename: openmediavault
    update_cache: true

- name: Install openmediavault package
  ansible.builtin.apt:
    name: openmediavault
    install_recommends: false
    allow_downgrade: true
    state: latest
    update_cache: true

# this command is needed to initialize the system
- name: Configure OMV DB
  ansible.builtin.command: "/usr/sbin/omv-confdbadm populate"
  when: omv_first_install
  changed_when: true

- name: After install, make sure we can still ssh to the machine
  ansible.builtin.user:
    name: "{{ item }}"
    group: _ssh
  with_items:
    - ansible
    - awaal

#sudo wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
