---
# tasks file for pxe_prep

- name: Set variable containing device name to zero
  ansible.builtin.set_fact:
    root_partition: "{{ ansible_mounts | json_query('[?mount == `/` && fstype == `ext4`].device | [0]') }}"

- name: Overwrite MBR to force PXE boot
  ansible.builtin.command: "dd if=/dev/zero of={{ root_partition[:-1] }} bs=446 count=1"
  changed_when: true

- name: Async reboot # noqa: ignore-errors
  ansible.builtin.command: shutdown -r now &
  ignore_errors: true
  changed_when: true
