---
# tasks file for pxe_prep

- name: Overwrite MBR to force PXE boot
  ansible.builtin.command: dd if=/dev/zero of=/dev/sda bs=446 count=1
  changed_when: true

- name: Async reboot # noqa: ignore-errors
  ansible.builtin.command: shutdown -r now &
  ignore_errors: true
  changed_when: true
