---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: defaults/main.yml
#
# Description: Creating a primary Active Directory Domain Controller.

# -- Samba4 AD settings --
#
# Variable(s):
#   smb_role           : 'additional'                          # Set samba4 role primary (only for initial setup), additional, member.
#   smb_workgroup      : 'LAB'                                 # Set workgroup (should be in capital letters).
#   smb_realm          : 'LAB.LOCAL'                           # Set realm (should be in capital letters).
#   smb_dns_servers    : '{{ ansible_default_ipv4.address }}'  # Set current ipv4 address.
#   smb_dns_forwarders : '8.8.8.8 8.8.4.4'                     # Set DNS forwarders.
#   smb_username       : 'Administrator'                       # Set administrator account.
#   smb_password       : 'Welcome01'                           # Set administrator password.
#   smb_site           : 'Amsterdam'                           # Sets the SiteName (prevents Default-Site-First-Site)
#   smb_rsyncd_pass    : 'Welcome01'                           # Sets the rsync daemon secret for sysvol sync
#
# Comment:
#   Override variable(s) by setting them in ./vars/main.yml
#
# yamllint disable rule:colons
smb_role: additional
smb_workgroup: TEST
smb_realm: TEST.ANDRECATHERINE.NET
smb_dns_servers: "{{ ansible_default_ipv4.address }}"
smb_dns_forwarder: 10.0.0.1 185.93.175.43
smb_username: Administrator
smb_password: "{{ vault_smb_password }}"
smb_site: Amsterdam
smb_rsyncd_pass: "{{ vault_smb_password }}"

smb_primary_dns: "{{ hostvars[groups['samba_ad_dc_primary'][0]]['ansible_host'] }}"
# If only provisioning main domain: secondary may be undefined, so in that case, do this:
smb_secondary_dns: "{{ hostvars[groups['samba_ad_dc_additional'][0]]['ansible_host'] }}"
# Use the following line when you have no additional dc's defined
# smb_secondary_dns: 185.93.175.43
# yamllint enable rule:colons
