---
# - name: Update apt cache.
#   ansible.builtin.apt:
#     update_cache: true

- name: Install required packages.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
    state: present

- name: Add log2ram repo using key from URL.
  ansible.builtin.deb822_repository:
    name: log2ram
    types: [deb]
    uris: http://packages.azlux.fr/debian/
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://azlux.fr/repo.gpg.key
    state: present
    enabled: true

- name: Update apt cache (and dist-upgrade) after log2ram repository is enabled.
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Ensure rsync is installed if the 'log2ram_use_rsync' option is true.
  ansible.builtin.apt:
    name: rsync
    state: present
  when: log2ram_use_rsync | bool

- name: Install log2ram.
  ansible.builtin.apt:
    name: log2ram
    state: present

- name: Set installed to true after installationss packages in Debian.
  ansible.builtin.set_fact:
    log2ram_installed: true
  when:
    - ansible_os_family == "Debian"

- name: Reboot system after log2ram is installed.
  ansible.builtin.reboot:
  when: log2ram_reboot_after_install | bool
