---
- name: Gather information on services in order to decide what to do.
  ansible.builtin.service_facts:

- name: Stop and disable the log2ram service.
  ansible.builtin.service:
    name: log2ram
    state: stopped
    enabled: false
  when: ansible_facts.services['log2ram.service'].state == "running"

- name: Uninstall log2ram through apt (Debian-based systems).
  ansible.builtin.apt:
    name: log2ram
    state: absent
    purge: true
  when: ansible_os_family == "Debian"

- name: Remove log2ram repo.
  ansible.builtin.deb822_repository:
    name: log2ram
    state: absent
