---
# defaults file for ad_backup
smb_username: Administrator
smb_password: "{{ vault_smb_password }}"
backup_path: "/tmp"
backup_max_age: "30d"
smb_backup_share: "//172.16.10.2/backup"
smb_backup_path: "/Informatica@HOME/Computers/ActiveDirectory"
local_backup_path: "/mnt/backup"
cifcreds: "{{ lookup('ansible.builtin.env', 'PRIVATE_REPO') | default('~') }}/ansible-vault/.cifscredential"
