---
# A normal config for the following three variables is false, true, false:
#  maintaining the tftp netboot config, refreshing pihole, but not re-installing fully
# netboot_download: true # controls downloading a new netboot.tar.gz
# Downloading a netboot image now depends on the age of the current image
netboot_max_age: "98d"
netboot_url: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz"
# do_pihole: true # will refresh adlists and domainlists - moved to vars_prompt
install_pihole: false # switch to (re-)install pihole

iface_dummy: "eth53"
iface_dummy_private_ipv4: "10.1.1.4"
iface_dummy_private_ipv6: "2a10:3781:3623:d0::1/64"

# My provider documents these on https://freedom.nl/page/servers
# Forwarder 1 and 2 are required
forward_dns_1: "185.93.175.43" # Google would be 8.8.8.8
forward_dns_2: "185.232.98.76" # Google would be 8.8.4.4
# Use 3 and 4 for IPv6. You can also leave them empty
forward_dns_3: "2a10:3780:2:52:185:93:175:43"
forward_dns_4: "2a10:3780:2:53:185:232:98:76"

adlists: "{{ lookup('file', 'myadlist.json') | from_json }}"

wl_exact: "{{ lookup('file', 'whitelist-exact.json') | from_json }}"
wl_regex: "{{ lookup('file', 'whitelist-regex.json') | from_json }}"
bl_exact: "{{ lookup('file', 'blacklist-exact.json') | from_json }}"
bl_regex: "{{ lookup('file', 'blacklist-regex.json') | from_json }}"

# For reference: the adlist table looks like:
# CREATE TABLE adlist
#  (
# 	id INTEGER PRIMARY KEY AUTOINCREMENT,
# 	address TEXT UNIQUE NOT NULL,
# 	enabled BOOLEAN NOT NULL DEFAULT 1,
# 	date_added INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
# 	date_modified INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
# 	comment TEXT,
# 	date_updated INTEGER,
# 	number INTEGER NOT NULL DEFAULT 0,
# 	invalid_domains INTEGER NOT NULL DEFAULT 0,
# 	status INTEGER NOT NULL DEFAULT 0
# );

# CREATE TABLE domainlist
# (
# 	id INTEGER PRIMARY KEY AUTOINCREMENT,
# 	type INTEGER NOT NULL DEFAULT 0,
# 	domain TEXT NOT NULL,
# 	enabled BOOLEAN NOT NULL DEFAULT 1,
# 	date_added INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
# 	date_modified INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
# 	comment TEXT,
# 	UNIQUE(domain, type)
# );
