---
# file: common/handlers/main.yml
- name: Update packages cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart rrdcached
  ansible.builtin.systemd_service:
    name: rrdcached
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
