---
- name: Remove existing container
  community.docker.docker_container:
    name: portainer
    state: absent
    purge_networks: true
    force_kill: true
  when: remove_existing_container

- name: Remove persistent data
  ansible.builtin.file:
    state: absent
    path: '{{ persistent_data_path.split(":") | first | string }}'
  when: remove_persistent_data
