---
# tasks file for virtualbox
# Follows: https://www.virtualbox.org/wiki/Linux_Downloads

- name: Add the VirtualBox apt repository
  ansible.builtin.deb822_repository:
    name: VirtualBox
    types: [deb]
    uris: "{{ vbox_repo_url }}"
    suites: "{{ vbox_apt_suite }}"
    components: "{{ vbox_apt_components }}"
    signed_by: "{{ vbox_apt_key_url }}"
    state: present
    enabled: true

- name: Install required VirtualBox packages
  ansible.builtin.apt:
    name:
      - "virtualbox-{{ vbox_install_version }}"
    update_cache: true
    state: present
