---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: handlers/main.yml
#
# Description: Creating a primairy Active Directory Domain Controller.

- name: Restart Samba
  ansible.builtin.systemd_service:
    state: reloaded
    name: samba-ad-dc.service
