---
- name: Force colors in .bashrc
  lineinfile:
    path: "{{ ansible_home }}/.bashrc"  # Set the actual path to the user's home directory
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: 'present'
  with_items:
    - { regexp: '^#?force_color_prompt', line: 'force_color_prompt=yes' }
  become: true
  become_user: "{{ ansible_user }}"
