---
# Note the use of "ansible_remote_tmp" - to prevent WARNINGS because of becoming an unprivileged user
- name: Force colors in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ interactive_home }}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^#?force_color_prompt", line: force_color_prompt=yes }
  become: true
  become_user: "{{ interactive_user }}"
  vars:
    ansible_remote_tmp: /tmp
