---
- name: Disable journaling on the root filesystem
  replace:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX="(.*)"'
    replace: 'GRUB_CMDLINE_LINUX="\1 rootflags=data=writeback"'

- name: Update GRUB configuration
  command: update-grub
  when: ansible_distribution == 'Debian'  # Add condition based on your distribution
