---
# file: common/tasks/main.yml
- name: Ensure required packages are present on systems
  ansible.builtin.import_tasks: prereq-packages.yml

- name: Make /tmp non-executable
  ansible.builtin.import_tasks: tmp-nonexec.yml

- name: Import tasks to ensure creation of unprivileged user
  ansible.builtin.import_tasks: unpriv-user.yml

- name: Import custom fact setting
  ansible.builtin.import_tasks: custom-fact.yml

- name: Import color-shell tasks for the common-role
  ansible.builtin.import_tasks: color-shell.yml

- name: Firmware block for Dell servers
  when: "'Dell' in ansible_board_vendor"
  block:
    - name: Import firmware tasks for Dell-based servers
      ansible.builtin.import_tasks: dell-firmware.yml

- name: Import journald tasks for the common-role
  ansible.builtin.import_tasks: edit-journald.yml

- name: Import hostname tasks for the common-role
  ansible.builtin.import_tasks: set-hostname.yml

- name: Import sudoers tasks for the common-role
  ansible.builtin.import_tasks: sudoers.yml

- name: Set the custom message of the day (motd)
  ansible.builtin.import_tasks: motd.yml

- name: Perform SSH daemon hardening
  ansible.builtin.import_tasks: ssh-config.yml
