---
- include_tasks: color-shell.yml
- include_tasks: firmware.yml
- include_tasks: edit-journald.yml
- include_tasks: inet6-manual.yml
- include_tasks: set-hostname.yml
- include_tasks: sudoers.yml
- include_tasks: powertop.yml
