---
- name: Ensure powertop is installed
  ansible.builtin.apt:
    name: powertop
    state: present

- name: Check whether service file already is there
  ansible.builtin.stat:
    path: /etc/systemd/system/powertop.service
  register: ps

- name: Place service file to run at startup for powertop
  ansible.builtin.template:
    src: etc/systemd/system/powertop.service.j2
    dest: /etc/systemd/system/powertop.service
    owner: root
    group: root
    mode: 0644
  when: not ps.stat.exists

- name: Trigger enabling of service and reload for powertop
  ansible.builtin.command: "{{ item }}"
  with_items:
  - systemctl daemon-reload
  - systemctl enable powertop.service
  become: true
  when: not ps.stat.exists