---
- name: Stage packages that are pre-requisites
  ansible.builtin.set_fact:
    _common_install_packages:
      - python3-debian
      - python3-requests
      - sudo

- name: Update all packages if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    upgrade: full
    autoclean: true
    autoremove: true
  timeout: 600 # on slow raspberries, updating may take a long time

- name: Install pre-requisite packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    name: "{{ _common_install_packages }}"
    state: latest
