---
- name: Create the force journal script
  ansible.builtin.template:
    src: ./templates/force_journal.sh.j2
    dest: /tmp/force_journal.sh
    mode: '0777'

- name: Run the script
  command: /tmp/force_journal.sh
  become: true
  become_user: root

- name: Reboot immediately
  ansible.builtin.reboot:

