---
- name: Get current filesystem features
  command: debugfs -R features {{ root_partition }}
  register: results
  tags:
    - dangerous

- name: Create variable for filesystem-check
  set_fact:
    fs_features: "{{ results.stdout_lines }}"
  tags:
    - dangerous
- debug:
    var: fs_features
  tags:
    - dangerous

- name: Create the force journal script
  ansible.builtin.template:
    src: ./templates/force_journal.sh.j2
    dest: /tmp/force_journal.sh
    mode: '0777'
  tags:
    - dangerous

- name: Run the script
  command: /tmp/force_journal.sh > /home/awaal/report.txt
  async: 60
  poll: 0
  become: true
  become_user: root
  when: fs_features is search("has_journal")
  tags:
    - dangerous

- ansible.builtin.meta: clear_host_errors
  tags:
    - dangerous

- name: Wait for system to become reachable
  wait_for_connection:
    delay: 20
    timeout: 60
  tags:
    - dangerous
