---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name:
      - docker
      - docker.io
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: docker_add_repo | bool

- name: Add Docker repo using key from URL.
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "{{ docker_apt_repository }}"
    suites: "{{ ansible_distribution_release }}"
    components: "{{ docker_apt_release_channel }}"
    signed_by: "{{ docker_apt_gpg_key }}"
    state: present
    enabled: true
  when: docker_add_repo | bool

- name: Update package cache after adding repo
  ansible.builtin.apt:
    update_cache: true
