---
# defaults file for vscode
vscode_apt_key_url: https://packages.microsoft.com/keys/microsoft.asc
vscode_repo_url: https://packages.microsoft.com/repos/code

# Used only for Debian/Ubuntu/Pop!_OS/Linux Mint. Switch 'stable' to 'nightly' if needed.
vscode_apt_suite: stable
vscode_apt_components: main

vscode_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
