---
# tasks file for pi-common
- name: Ensure python3-debian is present on Raspberry
  ansible.builtin.apt:
    name: python3-debian
    update_cache: true
    state: present

## Start by expanding the filesystem (when possible)
- name: Check whether FS is expandable
  ansible.builtin.command: raspi-config nonint get_can_expand
  register: fs_filled
  changed_when: false

- name: Print if FS is expandable or not
  ansible.builtin.debug:
    msg: Filesystem is expandable! [{{ fs_filled.stdout }}]
  when: fs_filled.stdout == '0'

- name: Expand Filesystem
  ansible.builtin.command: raspi-config nonint do_expand_rootfs
  when: fs_filled.stdout == '0'
  notify: Restart Raspberry
  changed_when: false

# N3 Disable predictable network interface names
- name: Get predictable network names status
  ansible.builtin.command: raspi-config nonint get_net_names
  register: pi_netnames
  changed_when: false

- name: Print current predictable network names status (0=enabled, 1=disabled)
  ansible.builtin.debug:
    msg: "Current network names status: {{ pi_netnames.stdout }}"

- name: Set predictable network names
  ansible.builtin.command: raspi-config nonint do_net_names {{ disable_netnames }}
  when: pi_netnames.stdout != disable_netnames
  notify: Restart Raspberry
  changed_when: true

# P2 SSH
- name: Check if SSH is disabled (1) or not (0)
  ansible.builtin.command: raspi-config nonint get_ssh
  register: ssh_status
  changed_when: false

- name: Print SSH status
  ansible.builtin.debug:
    msg: "SSH status is: {{ ssh_status.stdout }}"

- name: Set SSH
  ansible.builtin.command: raspi-config nonint do_ssh {{ disable_ssh }}
  when: ssh_status.stdout != disable_ssh
  notify: Restart Raspberry
  changed_when: true

# P3 VNC
- name: Get VNC status
  ansible.builtin.command: raspi-config nonint get_vnc
  register: vnc_status
  changed_when: false

- name: Print VNC status
  ansible.builtin.debug:
    msg: "VNC status is: {{ vnc_status.stdout }}"

- name: Set VNC
  ansible.builtin.command: raspi-config nonint do_vnc {{ disable_vnc }}
  when: vnc_status.stdout != disable_vnc
  notify: Restart Raspberry
  changed_when: true

# P4 SPI
- name: Get SPI status
  ansible.builtin.command: raspi-config nonint get_spi
  register: spi_status
  changed_when: false

- name: Print SPI status
  ansible.builtin.debug:
    msg: "SPI status is: {{ spi_status.stdout }}"

- name: Enable SPI
  ansible.builtin.command: raspi-config nonint do_spi {{ disable_spi }}
  when: spi_status.stdout != disable_spi
  notify: Restart Raspberry
  changed_when: true

# P5 I2C
- name: Get I2C status
  ansible.builtin.command: raspi-config nonint get_i2c
  register: i2c_status
  changed_when: false

- name: Print I2C status
  ansible.builtin.debug:
    msg: "I2C status is: {{ i2c_status.stdout }}"

- name: Enable I2C
  ansible.builtin.command: raspi-config nonint do_i2c {{ disable_i2c }}
  when: i2c_status.stdout != disable_i2c
  notify: Restart Raspberry
  changed_when: true

# P7 1-Wire
- name: Get Onewire status
  ansible.builtin.command: raspi-config nonint get_onewire
  register: onewire_status
  changed_when: false

- name: Print Onewire status
  ansible.builtin.debug:
    msg: "Onewire status is: {{ onewire_status.stdout }}"

- name: Set OneWire
  ansible.builtin.command: raspi-config nonint do_onewire {{ disable_1wire }}
  when: onewire_status.stdout != disable_1wire
  notify: Restart Raspberry
  changed_when: true

# P8 Remote GPIO
- name: Get rGPIO status
  ansible.builtin.command: raspi-config nonint get_rgpio
  register: rgpio_status
  changed_when: false

- name: Print rGPIO status
  ansible.builtin.debug:
    msg: "rGPIO status is: {{ rgpio_status.stdout }}"

- name: Set Remote GPIO
  ansible.builtin.command: raspi-config nonint do_rgpio {{ disable_gpio }}
  when: rgpio_status.stdout != disable_gpio
  notify: Restart Raspberry
  changed_when: true
