---
# tasks file for pi-hifiberry
- name: Comment out dtparam=audio=on
  ansible.builtin.replace:
    path: "{{ pi_config }}"
    regexp: (^dtparam=audio=on.*)
    replace: "# \\1"

- name: Add noaudio to vc4 overlay
  ansible.builtin.replace:
    path: "{{ pi_config }}"
    regexp: "^dtoverlay=vc4-.*kms-v3d.*"
    replace: "dtoverlay=vc4-kms-v3d,noaudio"

- name: Add hifiberry-dacplus to boot-config
  ansible.builtin.lineinfile:
    path: "{{ pi_config }}"
    regexp: "^dtoverlay=hifiberry.*"
    line: dtoverlay=hifiberry-dacplus
    state: present
    insertafter: '^[all]'
