---
# file: 08-infra-services.yml
- name: Deploy virtualized and containerized infra services onto endpoint_idx 0
  hosts:
    - infra_services:&portainer_server
  become: true
  roles:
    - waal70.vaultwarden # includes nginx-pm
    - waal70.authentik
    - waal70.backup

- name: Deploy infra services onto first agent
  hosts:
    - infra_services:&portainer_agent
  become: true
  roles:
    - waal70.forgejo
    - waal70.semaphore
    - waal70.debmirror
    - waal70.backup
  vars:
    endpoint_idx: 1  # These services will be deployed to the second endpoint (first outpost)
    backup_directories:
      - /appdata
      - /data
    backup_minute: "45"
  post_tasks:
    - name: Inform user of state of variable
      ansible.builtin.debug:
        msg: "host is {{ ansible_facts['hostname'] }}"
