---
- name: Dummy for pi5-02
  hosts:
    - pi5-02
  become: true
  gather_facts: true
  tasks:
    - name: "Debug the hostname"
      ansible.builtin.debug:
        msg: "Dummy task for {{ ansible_facts['hostname'] }}"

- name: Show info on specific host
  hosts:
    - pi5-01
  become: true
  gather_facts: true
  roles:
    - waal70.debmirror
  vars:
    endpoint_idx: 1

- name: Update the apt repository
  hosts: vb-test
  become: true
  roles:
    - waal70.docker
