---
- name: Dummy for pi5-02
  hosts:
    - pi5-02
  become: true
  gather_facts: true
  tasks:
    - name: "Debug the hostname"
      ansible.builtin.debug:
        msg: "Dummy task for {{ ansible_facts['hostname'] }}"

- name: Show info on specific host
  hosts:
    - pi5-01
  become: true
  gather_facts: true
  roles:
    - waal70.debmirror
  vars:
    endpoint_idx: 1
  post_tasks:
    - name: Run completed, so delete the marker
      ansible.builtin.file:
        path: /tmp/portainertje
        state: absent

- name: Update the apt repository
  hosts: localhost
  become: true
  tasks:
    - name: Update the regular apt repo
      ansible.builtin.deb822_repository:
        name: debian
        types: deb
        uris: http://debian.andrecatherine.net/
        suites:
          - trixie
          - trixie-updates
        components:
          - main
          - contrib
          - non-free
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

    - name: Update the security repo
      ansible.builtin.deb822_repository:
        name: debian-security
        types: deb
        uris: http://security.debian.org/debian-security/
        suites:
          - trixie-security
        components:
          - main
          - contrib
          - non-free
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
