---
# title: role-samba-ad-dc
#
# Author: André
# Version: 1.0
# File: tasks/debian-bookworm-additional.yml
#
# Description: Install samba and *join* a domain. This file for non-primary domain controllers

- import_tasks: debian-bookworm-shared.yml

- name: "Transfer krb5.conf.j2 to /etc/krb5.conf"
  ansible.builtin.template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf

- name: "Transfer resolv.conf.j2 to /etc/resolv.conf"
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf

- name: "Join as additional domain controller because of smb_role"
  ansible.builtin.command: samba-tool domain join {{ smb_realm }} --dns-backend=SAMBA_INTERNAL DC -U"{{ smb_workgroup }}\{{ smb_username }}" --password={{ smb_password }} --option='idmap_ldb:use rfc2307 = yes'
  when:
    - smb_dc_result.failed == true
    - smb_role == 'additional'
    - ad_database.stat.exists == false
  notify: Restart Samba

- name: "Always Enable Services"
  ansible.builtin.systemd_service:
    enabled: true
    masked: false
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service

- name: Obligatory reboot on joining domain, but only if join domain was executed in this run
  ansible.builtin.reboot:
    msg: "Ansible rebooting after joining domain"
  when: ad_database.stat.exists == false

- name: "Always restart samba-ad-dc.service"
  ansible.builtin.systemd_service:
    name: samba-ad-dc.service
    state: reloaded
