---
# title: ansible-role-samba4-primary-ad-dc
#
# Author: Luc Rutten
# Version: 1.0
# File: tasks/ubuntu-1604-amd64.yml
#
# Description: Creating a primairy Active Directory Domain Controller.

- import_tasks: debian-bookworm-shared.yml

- name: "Transfer resolv.conf.j2 to /etc/resolv.conf"
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf

- name: "Set {{ ansible_hostname }} as primary domain controller because of smb_role={{ smb_role }}"
  ansible.builtin.command: samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm={{ smb_realm }} --domain={{ smb_workgroup }} --adminpass={{ smb_password }}
  when:
    - smb_dc_result.failed == true
    - smb_role=="primary"
  notify: Restart Samba

- name: "Disable Services"
  systemd:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service
  when:
    - smb_dc_result.failed == true

- name: "back-Up the initial /etc/krb5.conf to /etc/krb5.conf.initial"
  copy:
    src: /etc/krb5.conf
    dest: /etc/krb5.conf.initial
    remote_src: yes
    force: no
  when:
    - smb_dc_result.failed

- name: "Copy /var/lib/samba/private/krb5.conf to /etc/krb5.conf"
  ansible.builtin.copy:
    src: /var/lib/samba/private/krb5.conf
    remote_src: true
    dest: /etc/krb5.conf
    force: yes

- name: "Always Enable Services"
  systemd_service:
    enabled: true
    masked: false
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service

- name: "Always restart samba-ad-dc.service"
  ansible.builtin.systemd_service:
    name: samba-ad-dc.service
    state: reloaded

- name: "Edit Fstab"
  replace:
    path: /etc/fstab
    regexp: 'errors=remount-ro 0'
    replace: 'user_xattr,acl,barrier=1,errors=remount-ro,relatime 0'
    backup: yes
  when:
    - smb_dc_result.failed
