---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: tasks/ubt-1804-amd64.yml
#
# Description: Creating a primairy Active Directory Domain Controller.

- import_tasks: debian-bookworm-shared.yml

- name: "Transfer krb5.conf.j2 to /etc/krb5.conf"
  template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf

- name: "Transfer resolv.conf.j2 to /etc/resolv.conf"
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf

- name: "Join {{ ansible_hostname }} as secondary domain controller because of smb_role={{ smb_role }}"
  ansible.builtin.command: samba-tool domain join {{ smb_realm }} --dns-backend=SAMBA_INTERNAL DC -U"{{ smb_workgroup }}\{{ smb_username }}" --password={{ smb_password }} --option='idmap_ldb:use rfc2307 = yes'
  when:
    - smb_dc_result.failed
  notify: Restart Samba

- name: "Always Enable Services"
  systemd_service:
    enabled: true
    masked: false
    name: "{{ item }}"
  with_items:
    - samba-ad-dc.service
    - smbd.service
    - nmbd.service
    - winbind.service

- name: "Always restart samba-ad-dc.service"
  ansible.builtin.systemd_service:
    name: samba-ad-dc.service
    state: reloaded
