---
# title: samba-ad-dc
#
- name: "For Debian bookworm - primary"
  import_tasks: debian-bookworm-primary.yml
  when:
    - smb_role == "primary"
    - ansible_architecture == "x86_64"
    - ansible_distribution_release == "bookworm"

- name: "For Debian bookworm - additional"
  import_tasks: debian-bookworm-additional.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_release == "bookworm"
    - ansible_architecture == "x86_64"

