---
# title: samba-ad-dc
#

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- name: "Build hosts file for SAMBA DC's"
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}} {{item}}.{{ smb_realm }}"
    state=present
  with_items: "{{ groups['samba_ad_dc_servers'] }}"


- name: "For Debian bookworm - primary"
  import_tasks: debian-bookworm-primary.yml
  when:
    - smb_role == "primary"
    - ansible_architecture == "x86_64"
    - ansible_distribution_release == "bookworm"

- name: "For Debian bookworm - additional"
  import_tasks: debian-bookworm-additional.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_release == "bookworm"
    - ansible_architecture == "x86_64"

- import_tasks: sysvol-sync.yml

