#!/bin/sh

###############################################################
#  Script     : 11-welcome
#  Author     : Petr Všetečka, Andre
#  Email      : vsetecka@cesnet.cz
#  Date       : 27/11/2018, 16/07/2024
#  Description: prints distro name and kernel version
#  Args       : none
###############################################################

clear

printf "\nSystem managed by Ansible"

printf "\nWelcome to "; lsb_release -ds
printf "  System: "; uname -snrvm
