---
# tasks file for debian-desktop
# Coming out from preseed and common role, first order of business is to install
# additional firmware packages:
# nouveau.modeset=0
- name: Fix GRUB nouveau errors and reboot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*quiet'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet nouveau.modeset=0"'
  register: grubfix

- name: Update grub # noqa: no-handler
  ansible.builtin.command: update-grub
  when: grubfix.changed
  changed_when: grubfix.changed

- name: Reboot after fixing GRUB # noqa: no-handler
  ansible.builtin.reboot:
  when: grubfix.changed
  changed_when: grubfix.changed

- name: Install (Intel) firmware packages
  ansible.builtin.apt:
    name:
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-sof-signed
      - intel-microcode
    state: present

- name: Check for presence of graphical desktop environment
  ansible.builtin.stat:
    path: "/etc/gnome"
  register: gnomestat

- name: Install the graphical desktop environment
  ansible.builtin.command:
    cmd: tasksel install desktop laptop
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  changed_when: true
  when: not gnomestat.stat.exists

- name: Ensure psutil is present # we need psutil to use dconf later on
  ansible.builtin.apt:
    name: python3-psutil
    state: present

- name: Ensure "'nl_NL.utf8'" is present as a locale
  community.general.locale_gen:
    name:
      - "nl_NL.UTF-8"
      - "en_US.UTF-8"
    state: present


- name: Add flatpak and Remmina remote desktop
  ansible.builtin.apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
      - remmina
    state: latest

- name: Configure flatpak repository
  ansible.builtin.command:
    cmd: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  changed_when: false

- name: Nuke firefox ESR that comes standard with GNOME
  ansible.builtin.apt:
    name: firefox-esr
    state: absent
    purge: true

- name: Install firefox using flatpak
  community.general.flatpak:
    name: org.mozilla.firefox
    state: latest

- name: Import tasks to get rid of bloatware
  ansible.builtin.import_tasks:
    file: kill-gnome-bloat.yml

- name: Import tasks to customize GNOME
  ansible.builtin.import_tasks:
    file: customize-gnome.yml
  become_user: "{{ interactive_user }}"
